# Parallelizing Neural Network Training with Tensorflow 

In [4]:
import tensorflow as tf
import numpy as np

In [2]:
# Create a graph
g = tf.Graph()
with g.as_default():
    x = tf.placeholder(dtype = tf.float32,
                       shape = (None), name = 'x')
    w = tf.Variable(2.0, name = 'weight')
    b = tf.Variable(0.7, name = 'bias')
    
    z = w*x + b
    init = tf.global_variables_initializer()

# Create a session and pass in graph g
with tf.Session(graph = g) as sess:
    # Initialize w and b
    sess.run(init)
    # Evaluate z
    for t in [1.0, 0.6, -1.8]:
        print('x = %4.1f ==> z = %4.1f' % (t, sess.run(z, feed_dict = {x:t})))

x =  1.0 ==> z =  2.7
x =  0.6 ==> z =  1.9
x = -1.8 ==> z = -2.9


In [3]:
with tf.Session(graph = g) as sess:
    sess.run(init)
    print(sess.run(z, feed_dict = {x:[1., 2., 3.]}))

[2.7 4.7 6.7]


## Working with array structures 

In [7]:
g = tf.Graph()
with g.as_default():
    x = tf.placeholder(dtype = tf.float32,
                       shape = (None, 2, 3), name = 'input_x')
    x2 = tf.reshape(x, shape = (-1, 6),
                    name = 'x2')
    
    ## Calculate the sum of each column
    xsum = tf.reduce_sum(x2, axis = 0, name = 'col_sum')
    
    ## Calculate mean of each column
    xmean = tf.reduce_mean(x2, axis = 0, name = 'col_mean')
    
# Create a session and pass graph to it
with tf.Session(graph = g) as sess:
    x_array = np.arange(18).reshape(3, 2, 3)
    
    print('Input shape: ', x_array.shape)
    print('Reshaped:\n', sess.run(x2, feed_dict = {x:x_array}))
    print('Column sum: ', sess.run(xsum, feed_dict = {x:x_array}))
    print('Column mean: ', sess.run(xmean, feed_dict = {x:x_array}))

Input shape:  (3, 2, 3)
Reshaped:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]]
Column sum:  [18. 21. 24. 27. 30. 33.]
Column mean:  [ 6.  7.  8.  9. 10. 11.]


## Developing a simple model with low level tensorflow API 